name: wordpress deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: checkout repo
      uses: actions/checkout@v3


        
        
  zip-repo:
    runs-on: ubuntu-latest
    timeout-minutes: 10 
    needs: [deploy]

    steps:
    - name: Generate Report
      uses: actions/upload-artifact@v2
      with:
        name: HTML_Report
        path: githat-Hero/test
        retention-days: 5


