name: wordpress deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: run commands
        run: |
          pwd
          zip -r myarchive.zip test
          cd test
          ls
      
    
      
 


