name: WordPress deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    
    - name: Sync
      env:
        dest: './myfile'
      run: |
        rsync  ./ ${{env.dest}}

      
    
      
 


