name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world
        run: echo "helo world"
        shell: bash
        
      - name: Remove theme.zip
        uses: JesseTG/rm@v1.0.3
        with:
         path: theme.zip

  GoodBye:
    runs-on: ubuntu-latest
    steps:
      - name: good bye
        run: echo "good bye"
        shell: bash
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r theme.zip . -i  .
      - uses: actions/upload-artifact@v3
        with:
          name: Themes
          path: theme.zip
  
 
     
