name: wordpress deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: checkout repo
      uses: actions/checkout@v3


        
        
  zip-repo:
    runs-on: ubuntu-latest
    timeout-minutes: 10 
    needs: [deploy]

    steps:
    - uses: montudor/action-zip@v1
      with:
       args: zip -qq -r dir.zip . -i test


