name: wordpress deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Remove theme.zip
      uses: JesseTG/rm@v1.0.3
      with:
        path: githat-Hero/test
        
        
  zip-repo:
    runs-on: ubuntu-latest
    timeout-minutes: 10 
    needs: [deploy]

    steps:
    - name: Generate Zip file
      uses: actions/upload-artifact@v3
      with:
        path: githat-Hero/test
        if-no-files-found: error
