name: Build release zip

on:
  push:
    branches:
    - main
env:
  build_directory: ${{github.workspace}}/BUILD
  release_name: build_${{github.run_number}}

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.release_name}}
        path: ${{env.build_directory}}/test.zip
      
    
      
 


